# Generated by Django 3.1.7 on 2021-03-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('date_of_birthday', models.CharField(max_length=20)),
                ('marital_status', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=30)),
                ('quote', models.TextField(blank=True, db_index=True)),
                ('biography', models.TextField(blank=True, db_index=True)),
                ('pic', models.ImageField(upload_to='pages/static/images')),
            ],
        ),
    ]
