# Generated by Django 3.1.7 on 2021-03-28 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_info',
            name='date_submitted',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
